<?php
/**
 * @file
 * Provides a Views plugin for displaying content in a Masonry layout.
 */

/**
 * Implements hook_views_api().
 */
function masonry_views_views_api() {
  return array('api' => 3);
}

/**
 * Preprocess function for views_view_masonry.tpl.php.
 */
function template_preprocess_views_view_masonry(&$vars) {
  // Run preprocess function for unformatted style
  template_preprocess_views_view_unformatted($vars);

  // Get view options
  $view = $vars['view'];
  $options = $vars['options'];

  // Create a unique masonry-container ID
  $unique_masonry_container = drupal_html_id('view-masonry-container');
  $vars['container_id'] = $unique_masonry_container;

  // Display content in a Masonry layout
  $container = '#' . $unique_masonry_container;
  $options['masonry_item_selector'] = '.masonry-item';
  masonry_apply($container, $options);
}

