<?php
/**
 * @file
 * Provides a Views plugin for displaying content in a Masonry layout.
 */

/**
 * Implements hook_autoload_info().
 */
function masonry_views_autoload_info() {
  return array(
    'views_plugin_style_masonry_views' => 'views_plugin_style_masonry_views.inc',
  );
}

/**
 * Implements hook_views_api().
 */
function masonry_views_views_api() {
  return array('api' => 3);
}

/**
 * Preprocess function for views_view_masonry.tpl.php.
 */
function template_preprocess_views_view_masonry(&$vars) {
  // Run preprocess function for unformatted style
  template_preprocess_views_view_unformatted($vars);

  // Add some default CSS.
  backdrop_add_css(backdrop_get_path('module', 'masonry_views') . '/css/masonry_views.css');

  // Get view options
  $view = $vars['view'];
  $options = $vars['options'];

  // Display content in a Masonry layout
  $container = '.view-' . backdrop_clean_css_identifier($view->name) . '.view-display-id-' . $view->current_display . ' > .view-content';
  if (!empty($options['grouping'])) {
    $vars['grouping'] = true;
    static $groupid;
    $container .= ' .masonry-group-' . ++$groupid;
    $vars['prefix'] = "<div class=\"masonry-group masonry-group-$groupid\">";
    $vars['suffix'] = "</div>";
  }
  $options['masonry_item_selector'] = '.masonry-item';
  masonry_apply($container, $options);
}

//Temporarily patch in the plugin hook below since the autoload doesn't seem to be working from a separate file.

/**
 * @file
 * Provide views data and handlers for masonry_views.module.
 */

/**
 * Implements hook_views_plugins().
 */
function masonry_views_views_plugins() {
  return array(
    'style' => array(
      'masonry_views' => array(
        'title' => t('Masonry'),
        'handler' => 'views_plugin_style_masonry_views',
        'uses options' => TRUE,
        'help' => t("Display content in a Masonry layout."),
        'theme' => 'views_view_masonry',
        'theme file' => 'views-view-masonry.tpl.php',
        'theme path' => backdrop_get_path('module', 'masonry_views'),
        'type' => 'normal',
        'uses row plugin' => TRUE,
        'uses row class' => TRUE,
        'uses grouping' => TRUE,
      ),
    ),
  );
}

